---
title: "FinalProject_STAT627"
author: "Thaina Gomez"
date: "3/16/2025"
output: html_document
---

```{r}
library(tidyverse)
library(caret)
library(car)
library(ggplot2)
library(MASS)
library(dplyr)

data <- read.csv('diabetes_prediction_dataset.csv')
head(data)
```

```{r}
str(data)
summarise_all(data, ~sum(is.na(.)))
```
```{r}
# Converting categorical variables into factors
data$gender <- as.factor(data$gender)
data$hypertension <- as.factor(data$hypertension)
data$heart_disease <- as.factor(data$heart_disease)
data$smoking_history <- as.factor(data$smoking_history)
```
```{r}
# Exploratory Data Analysis (EDA)
# Visualizing HbA1c distribution
hist(data$HbA1c_level, breaks = 30, col = 'lightblue', main = 'Distribution of HbA1c Levels', xlab = 'HbA1c')
```
```{r}
# Correlation heatmap for numeric predictors
numeric_vars <- data %>%
  dplyr::select(age, bmi, blood_glucose_level, HbA1c_level)
corr_matrix <- cor(numeric_vars, use = 'complete.obs')
print(corr_matrix)
```
```{r}
# Scatterplots to check linear relationships
pairs(numeric_vars, main = "Scatterplot Matrix")
```
```{r}
# Regression Model (RO1): Predicting HbA1c
model_full <- lm(HbA1c_level ~ age + bmi + blood_glucose_level + smoking_history + hypertension + heart_disease, data = data)
summary(model_full) 
```
```{r}
# Checking multicollinearity
vif_values <- vif(model_full)
print(vif_values)
```
```{r}
# Stepwise feature selection
model_step <- stepAIC(model_full, direction = "both")
summary(model_step)
```
```{r}
# Residual Diagnostics for normality, homoscedasticity, and outliers
par(mfrow=c(2,2))
plot(model_step)
```
```{r}
# K-Fold Cross-Validation
set.seed(123)
train_control <- trainControl(method = "cv", number = 10)
cross_val_model <- train(HbA1c_level ~ age + bmi + blood_glucose_level + smoking_history + hypertension + heart_disease,
                         data = data, 
                         method = "lm", 
                         trControl = train_control)
print(cross_val_model)
```
```{r}
# MSE as performance metric
predicted <- predict(model_step, newdata = data)
mse <- mean((data$HbA1c - predicted)^2)
print(paste("Mean Squared Error (MSE):", mse))
```